language: node_js
node_js:
  - "8"
  - node

# script: echo "Running tests against $(node -v)..."

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npm run coverage

#deploy:
#  provider: npm
#  email: "krupnik.yuri@gmail.com"
#  api_key: "ds"
#  on:
#    tags: true
#    branch: master
