language: node_js
node_js:
  - '11'

# script: echo "Running tests against $(node -v)..."

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: Produce Coverage
      node_js: '11'
      script: npm run test:coveralls
    - stage: Dynamyc E2E Coverage
      node_js: '11'
      script: npm run test:e2e


#env:
#  global:
#    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
#    #   via the "travis encrypt" command using the project repo's public key
#    - secure: "WNuqeIK7/jDRfNixGebiDGe1/bwLNcIlVQg6vdB/6mAmfr9jX2i+t1sWOzhkW8VdlsqVMAamHZleImNfTiWw7jOV6099sJzBFb7Idwr6AXa+cn+NbeN/FefvyxAyWXqAPDwDo6tz4YDNMscPT228dYBJg82+21CsRJWC6gD/H7RcuKUWZ8BuiyNnzBD44hlFtckQ1BpZdO4okIDVM4OUtjST16qabl8pi9hzYj8ScDzD3gIXTtv1JRhhcCv7Ffe6uGrThNOPjgRMngbNLa76DPV+YCoPtwgZkAjyEese3A0MAJVFUnOhQGIKk/peTTFUQO9ccDQG2JC8LPfE8ln6FbmPhWZtHh1ofBHKf1vFTyMGi/zL15TIHbCqqZYvczTCgzb4fpwoxC59LWiMoUW9GvOHKeRdozYZJY/YVJGou3PvFDKZziAORAiaKVN+YC+9ej/pqN91KCiBB8W+3fDhBbgQb3P4m8GPrrQJlMi851NA6eARY8ngh0Y4RWIbBmUXH3ruHiLyzfenjphazwNVMx99+0NkoVl233ss3N7smXZ7s48tKgirKTuLNPhK0Gr+7gvJhQ18D7zG8kEo6EP/xtkcezALNl6DStM9aCE7yInm5qJmB5Mfu/WEDOmEfVs/FFvkzayEFqp8bhuFoeL1wtBgO83+3bO0L01aXuQwlec="
#
#before_install:
#  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
#
#addons:
#  coverity_scan:
#    project:
#      name: "yurikrupnik/custom-react"
#      description: "<Your project description here>"
#    notification_email: krupnik.yuri@gmail.com
#    build_command_prepend: npm run test
#    build_command: npm run build
#    branch_pattern: coverity_scan


deploy:
  provider: npm
  email: "krupnik.yuri@gmail.com"
  api_key: "65c450c8-2867-4120-ac2d-2a216d3a7a57"
  on:
    tags: true
    branch: master
