language: node_js
node_js:
  - "8"
  - node

# script: echo "Running tests against $(node -v)..."

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage --coverageReporters=text-lcov | coveralls

deploy:
  provider: npm
  email: "krupnik.yuri@gmail.com"
  api_key: "6bdfedd7-be9a-4d4f-aa3d-a804901ee3da"
#  on:
#    tags: true
#    branch: master
