version: 2
#node10: &node10
#  working_directory: ~/repo
#  docker:
#    - image: circleci/node:10

node8: &node8
  working_directory: ~/repo
  docker:
    - image: circleci/node:8

node9: &node9
  working_directory: ~/repo
  docker:
    - image: circleci/node:9

node10: &node10
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

node11: &node11
  working_directory: ~/repo
  docker:
    - image: circleci/node:11

node12: &node12
  working_directory: ~/repo
  docker:
    - image: circleci/node:12

jobs:
  test_node_8:
    <<: *node8
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
  test_node_9:
    <<: *node9
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
  test_node_10:
    <<: *node10
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
  test_node_11:
    <<: *node11
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
  test_node_12:
    <<: *node12
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
  test:
    <<: *node10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install
      - run:
          name: Run tests
          command: npm run test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  build:
    working_directory: ~/tmp/local
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install
      - run:
          name: Run tests
          command: npm build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: /tmp/workspace
          paths: .

  deploy:
    <<: *node10
    steps:
#      - attach_workspace:
#            at: /tmp/workspace
      - checkout
      - run: npm install
      - run: npm run build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test_and_nodes:
    jobs:
      - test_node_8
      - test_node_9
      - test_node_10
      - test_node_11
      - test_node_12

  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test

  test-deploy:
    jobs:
      - deploy:
        requires:
          - build
          - test
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
