version: 2
#node10: &node10
#  working_directory: ~/repo
#  docker:
#    - image: circleci/node:10

node6: &node6
  working_directory: ~/repo
  docker:
    - image: circleci/node:6

node7: &node7
  working_directory: ~/repo
  docker:
    - image: circleci/node:7

node8: &node8
  working_directory: ~/repo
  docker:
    - image: circleci/node:8

node9: &node9
  working_directory: ~/repo
  docker:
    - image: circleci/node:9

node10: &node10
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

node11: &node11
  working_directory: ~/repo
  docker:
    - image: circleci/node:11

node12: &node12
  working_directory: ~/repo
  docker:
    - image: circleci/node:12

jobs:
  test_node_6:
    <<: *node6
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
  test_node_7:
    <<: *node7
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
  test_node_8:
    <<: *node8
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
  test_node_9:
    <<: *node9
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
  test_node_10:
    <<: *node10
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
  test_node_11:
    <<: *node11
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
  test_node_12:
    <<: *node12
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
  test:
    <<: *node10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run:
          name: Run tests
          command: npm run test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  build:
    <<: *node9
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm run test
#      - run: # run coverage report
#          name: code-coverage
#          command: npm run test:coveralls
#      - store_artifacts: # special step to save test results as as artifact
#           # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
#           path: test-results.xml
#           prefix: tests
#      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
#           path: coverage
#           prefix: coverage
#      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
#           path: test-results.xml

#  deploy:
#    <<: *node10
#    steps:
#      - attach_workspace:
#          at: ~/repo
#      - run:
#          name: Authenticate with registry
#          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
#      - run:
#          name: Publish package
#          command: npm publish

workflows:
  version: 2
  test_and_release:
    jobs:
      - test_node_6
      - test_node_7
      - test_node_8
      - test_node_9
      - test_node_10
      - test_node_11
      - test_node_12

#      - test
#      - build
#      - deploy:
#          requires:
#            - test
