version: 2
jobs:
  stam:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node
    steps:
      - checkout
      -
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node
      - run:
          name: abc
          command echo $NODE_ENV
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm run test
      - run:
          name: coverage
          command: jest --coverage --coverageReporters=text-lcov | coveralls
